name: Build and Release .exe

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: windows-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt   # Installe les dépendances de votre projet

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build .exe file
        run: |
          PyInstaller --name SBM --onefile --windowed --icon=icone.ico --add-data "locale/;./locale/" --collect-all customtkinter run.py
        shell: bash

      - name: Upload .exe to Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}  # Utilise le tag pour créer la Release
          name: Release ${{ github.ref_name }}
          artifacts: dist/SBM.exe   # Chemin de votre fichier .exe généré
          draft: true 
