name: Lint and release .exe on Github
on: [push]

jobs:
  lint:
    runs-on:  ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Analysing the code with flake8
      run: |
        flake8 --extend-ignore E501 $(git ls-files '*.py')

  build_exe:
    needs: [lint]
    runs-on:  windows-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    - name: Build exe file
      run: |
        python -m PyInstaller --name SBM --onefile --windowed --icon=icone.ico --add-data="locale/:./locale/" --collect-all customtkinter run.py --clean

    - name: Upload .exe to Release
      uses: ncipollo/release-action@v1
      with:
        tag: Test
        name: Release SBM
        artifacts: dist/SBM.exe
        draft: true
